### ISSUE TITLE
Searching on a subject (connection to a patient) gives 0 matches

### ISSUE THREAD

**Issue by Tagertswe** [jmiddleton/cassandra-fhir-index#2]
I believe I found another bug regarding searching on a subject.

SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,'resource_type:Observation AND subject:55678')  LIMIT 50;

Matches: 0

Type of rows in database:

Row[obs109, 1, Mon Aug 22 08:27:57 CEST 2016, test, {"resourceType":"Observation","category":{"text":"MDC_TTHOR_RESP_RATE"},"subject":{"reference":"55678"},"effectiveDateTime":"2016-08-22T08:27:57","valueQuantity":{"value":15}}, json, Observation, active]

I also tried another query, incase the subject reference field only interprets characters:

SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,'resource_type:Observation AND subject:testPatient')  LIMIT 50;

Matches: 0

rows contained in database:
Row[obs43, 1, Mon Aug 22 08:31:20 CEST 2016, test, {"resourceType":"Observation","category":{"text":"MDC_TTHOR_RESP_RATE"},"subject":{"reference":"testPatient"},"effectiveDateTime":"2016-08-22T08:31:20","valueQuantity":{"value":15}}, json, Observation, active]

I also tried to enable the debug logging for luceneService:
The following lines were inserted in $CASSANDRA_HOME/conf/logback.xml

  <logger name="i.p.fhir.index.lucene.LuceneService" level="DEBUG" />

  <logger name="io.puntanegra.fhir.index.lucene.LuceneService" level="DEBUG" />

DEBUG output:

DEBUG [SharedPool-Worker-2] 2016-08-22 08:43:46,064 LuceneService.java:265 - Searching in idx_fhir_resources
count: 50
after: null
query: CachingWrapperQuery(+resource_type:Observation +subject:55678)
 sort: null
DEBUG [SharedPool-Worker-1] 2016-08-22 08:43:54,100 LuceneService.java:265 - Searching in idx_fhir_resources
count: 50
after: null
query: CachingWrapperQuery(+resource_type:Observation +subject:55678)
 sort: null

DEBUG [SharedPool-Worker-1] 2016-08-22 08:53:47,548 LuceneService.java:265 - Searching in idx_fhir_resources
count: 50
after: null
query: CachingWrapperQuery(+resource_type:Observation +subject:testPatient)
 sort: null

Am I able to get even more debug output than this by the way?

I also tried searching on the example data provided by you in this project:
SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,'resource_type:Observation AND subject:Patient\/example')  LIMIT 50;

query execution time in ms: 12
size of return set is: 0

But no success.

My search index structure:

 CREATE CUSTOM INDEX idx_fhir_resources ON FHIR_RESOURCES (content)
     USING 'io.puntanegra.fhir.index.FhirIndex'
     WITH OPTIONS = {
        'refresh_seconds' : '5',
        'search': '{
            resources : {
               Patient : ["name", "identifier", "family", "email", "active"],
               Observation : ["category", "date", "subject"]
            }
        }'
     };

**Comment by jmiddleton** [comment]
Hi Martin,

i have committed some changes to support reference values. However, please check https://www.hl7.org/fhir/search.html#reference and https://www.hl7.org/fhir/references.html#Reference for more details as I don't know if your data (`"reference":"55678"`) is valid. 

At the moment, only references by `[type]/[id]` are supported i.e.: `Patient/123`

Regarding the logs, are you able to see something like:

`DEBUG LuceneService - Indexing Document<indexed,tokenized<subject:Patient/example23> indexed,omitNorms,indexOptions=DOCS<date:20160817071435> ....`

Let me know if the fix is working...

Cheers,
Jorge

**Comment by Tagertswe** [comment]
Hello Jorge,

Sorry for the late reply, I fell ill during the week and had to recover.

I am happy to report your fix worked!

Query:
SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,'resource_type:Observation AND subject:Patient\/5567 AND date:20160824112642 ')  LIMIT 50;

2 matches, as I expected.

Rows in database:
Row[obs40, 1, Wed Aug 24 11:26:42 CEST 2016, test, {"resourceType":"Observation","category":{"text":"MDC_ECG_HEART_RATE"},"subject":{"reference":"Patient/5567"},"effectiveDateTime":"2016-08-24T11:26:42","valueQuantity":{"value":60}}, json, Observation, active]

And yes, I received additional debug logging when inserting an object:

DEBUG [SharedPool-Worker-1] 2016-08-24 11:27:33,018 LuceneService.java:153 - Indexing Document<indexed,omitNorms,indexOptions=DOCS<date:20160824112733> indexed,tokenizedsubject:Patient/5567 indexed,tokenizedcategory:MDC_TTHOR_RESP_RATE indexed,tokenized<resource_type:Observation> indexed,tokenized,omitNorms,indexOptions=DOCS,numericType=LONG,numericPrecisionStep=16,docValuesType=NUMERIC<_token:-7119765985465728893> stored,indexed,omitNorms,indexOptions=DOCS,docValuesType=SORTED<_partition_key:[6f 62 73 31 34 33]> stored,indexed,omitNorms,indexOptions=DOCS,docValuesType=SORTED<_primary_key:[0 8 9d 31 82 8e f0 68 0 83 0 0 6 6f 62 73 31 34 33 0 0 12 0 4 0 0 0 1 0 0 8 0 0 1 56 bb e0 47 88 0 0]>> with term _primary_key:[0 8 9d 31 82 8e f0 68 0 83 0 0 6 6f 62 73 31 34 33 0 0 12 0 4 0 0 0 1 0 0 8 0 0 1 56 bb e0 47 88 0 0] in idx_fhir_resources

I have another inquiry, more like of how extensive it would be to implement support for the following feature and if it could be done.

I'm working with simulated, as well as live array data coming from an Intellivue machine from an ICU,
Since the array data gathered could be all from 500 - 1000 values it would be efficient to store all the values as a json string as you have in your current implementation of Cassandra FHIR.

 It is possible to insert it, however i'm getting exceptions when trying to search for it, so I assume it's not implemented.

The interesting part would be to identify one code or category, one date, one subject in that json containing multiple values as the one described below.

I have attached an example how it would look like:
_The following json was generated by collecting Observations and inserting into a bundle using hapi fhir_
http://pastebin.com/4LFUjJNR
That code could be pasted into the json generator at : http://www.json-generator.com/ for a nicer printout.

Tips and pointers and feedback regarding this inquiry is welcome :)

kind regards,
Martin

**Comment by jmiddleton** [comment]
Hi Martin,

Thank you for verifying the fix. I will close the defect.

Regarding your question, I think for indexing and searching it would be better to store each Observation, not the Bundle but each individual Observation. In this case I would assume you would be able to search for Observation that meet certain criteria. 

I checked your example and the Observation is the same, but I believe it’s only an example. Are you planing to have more information like Observation.device to see which device generates the data? 

Let me know what do you think?

Regards,
Jorge
